### ISSUE TITLE
No logs in SumoLogic

### ISSUE THREAD

**Issue by ijunaid8088** [wgregorian/ansible-sumocollector#13]
Hello.

we are using sumocollector to get the logs for our application but for last 4 days we are not getting any log through this. the JSON file we are using is
```
{
"api.version": "v1",
"sources": [
{
"name": "evercam-media",
"sourceType": "LocalFile",
"automaticDateParsing": true,
"multilineProcessingEnabled": "False",
"useAutolineMatching": true,
"forceTimeZone": false,
"timeZone": "UTC",
"category": "evercam-media",
"pathExpression": "/opt/evercam_media/log/erlang.log.*"
}
,
{
"name": "seaweedfs",
"sourceType": "LocalFile",
"automaticDateParsing": true,
"multilineProcessingEnabled": "False",
"useAutolineMatching": true,
"forceTimeZone": false,
"timeZone": "UTC",
"category": "seaweedfs",
"pathExpression": "/var/log/upstart/seaweedfs.log"
}
]
}
```

It was working fine but now few days it just not showing any log

**Comment by kbroughton** [comment]
Did you make any changes to the sumo deployment or configs?
this looks more like a question for sumologic, but here are some troubleshooting tips:

If there are errors in a source file, it may be difficult to discover. You can check in the UI by seeing if the file-name shows up in a collector's sources. You may inspect the json for the source by clicking the info icon. You can find the errors by changing the source while tailing collector.log in another shell: > tail -f /path/to/collector.log | grep blade

**Comment by wgregorian** [comment]
Not directly associated. Closing.
