### ISSUE TITLE
Destination directory /usr/lib/systemd/system does not exist

### ISSUE THREAD

**Issue by gadelkareem** [wgregorian/ansible-sumocollector#16]
Running in Vagrant Ubuntu16.04
```
TASK [wgregorian.sumocollector : install systemd unit for sumologic] ***********
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /usr/lib/systemd/system does not exist"}
```

**Comment by sheyd** [comment]
Seeing this on Ubuntu 16.04 Linode instance.

**Comment by sheyd** [comment]
Referencing https://github.com/chef/chef-server/issues/572, seems like creating the missing directory fixes the issue. PR incoming.

**Comment by sheyd** [comment]
Found some further errors on testing. Will try fixing and updating here.

**Comment by wgregorian** [comment]
Will merge PR ASAP.

**Comment by davidknaack** [comment]
Was this fixed? I don't see the PR.
